#!/usr/csshare/bin/python

import re 
import sys

# check for mandatory command line arguments 
mandatory_args = {'-n' : '<name>', '-g' : '<gid>'}

def print_usage():
    usage = ''
    for s in [key + ' ' + mandatory_args[key] for key in mandatory_args]:
        usage += s + ' '
    sys.stderr.write('Usage: ' + usage + '\n') 

arguments = sys.argv[1:]
if len(arguments) is not 2 * len(mandatory_args):
    sys.stderr.write('Error: wrong number of command line arguments.\n')
    print_usage()
    sys.exit(1)

args = {}
for i in range(0, len(arguments), 2):
    if arguments[i] not in mandatory_args:
        sys.stderr.write('Error: unrecognized command line argument "' + arguments[i] + '"\n')
        print_usage()
        sys.exit(1)
    args[arguments[i]] = arguments[i + 1]
    
# check if group name is alphanumeric 
if not args['-n'].isalnum():
    sys.stderr.write('Error: group name must be alphanumeric\n')
    sys.exit(1)

# check if the gid is numeric and between 0 and 65535
if not args['-g'].isdigit() or not 0 <= int(args['-g']) <= 65535:
    sys.stderr.write('Error: gid must be numeric and between 0 and 65535\n')
    sys.exit(1)

# read the group file 
f = open('etc/group')
lines = [line.strip() for line in f.readlines() if line.strip() != '' and line[0] != '#']

# check if the group name or gid is already present 
for line in lines:
    if args['-n'] == line[:line.find(':')]:
        sys.stderr.write('Error: group name already exists.\n')
        sys.exit(1)
    line = line[line.find(':') + 1:]
    line = line[line.find(':') + 1:]
    if args['-g'] == line[:line.find(':')]:
        sys.stderr.write('Error: gid already exists.\n')
        sys.exit(1)
        
