#!/usr/csshare/bin/python

# Daniel de Haas, Oliver Chou
# 3/12/13
# CS 183 - Winter '13
# Project #2 - archive_user

import os
import sys
import datetime
import time

from Users import User, Users 
from Logger import Logger

# start logger
logger = Logger()

# check mandatory arguments
mandatory_args = {'-l' : '<login>'}

def print_usage():
    usage = ''
    for s in [key + ' ' + mandatory_args[key] for key in mandatory_args]:
        usage += s + ' '
    sys.stderr.write('Usage: ' + usage + '\n') 

arguments = sys.argv[1:]
if len(arguments) is not 2 * len(mandatory_args):
    sys.stderr.write('Error: wrong number of command line arguments.\n')
    print_usage()
    sys.exit(1)

args = {}
for i in range(0, len(arguments), 2):
    if arguments[i] not in mandatory_args:
        sys.stderr.write('Error: unrecognized command line argument "' + arguments[i] + '"\n')
        print_usage()
        sys.exit(1)
    args[arguments[i]] = arguments[i + 1]

# check to see if login exists
user = args['-l']
passwd = "./etc/passwd"
if user in Users(passwd).users:
	unix_timestamp = int(time.time())
	timestamp = datetime.datetime.now().strftime('%Y%m%d%H%M%S') 

	# moving files 
	homeDir = "./home/%s" % (user)
	archiveDir = "./archived_homedirs/%s.%s" % (user, unix_timestamp)
	cmdStr = "mv %s %s" % (homeDir, archiveDir)

	os.system(cmdStr)

	# backing up ./etc/passwd file + loading file
	f = open(passwd, 'r')
	lines = f.readlines()
	f.close()

	cmdStr = "mv {0} {1}.{2}".format(passwd, passwd, timestamp)
	os.system(cmdStr)

	# removing user line from passwd file
	fout = open('./etc/passwd', 'w')
	for line in lines:
			if line[:line.find(':')] == args['-l']:
				pass
			else:
				fout.write(line)
	fout.close()
	
	infoMsg = "Archived %s's home dir.\n" % (user)
	logger.print_info(sys.argv[0], infoMsg) 
else:
	errorMsg = "User {0} doesn't exist!\n".format(user)
	logger.print_warn(sys.argv[0], errorMsg)
	sys.stderr.write(errorMsg)
	sys.exit(1)
